name: flowerpot
description: flowerpot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.3.0
  injectable: ^2.4.0
  get_it: ^8.0.2
  flutter_gen: any
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.11

  domain:
    path: ./packages/domain

  data:
    path: ./packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_native_splash: ^2.3.10
  injectable_generator: ^2.4.0
  json_serializable: ^6.6.0
  flutter_launcher_icons: "^0.14.1"

dependency_overrides:
  meta: ^1.12.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/illustrations/
    - assets/logos/
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path_android: "assets/logos/primary.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FFFAFA"
  adaptive_icon_foreground: "assets/icons/img.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/img.svg"

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true